import type { Metadata } from "next";
import "../globals.css";
import Navbar from "../../../components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="content">
            <div className="left titlebar">
              <h1 style={{ lineHeight: '1.9rem'}}>Samuel Morgan Anderson</h1>
            </div>
            <div className="right">
              <Navbar />
            </div>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
