import type { Metadata } from "next";
import "../globals.css";
import Navbar from "../../../components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navBarLinks: Array<{
    label: string,
    to: string
  }> = [
    {
      label: "About",
      to: "/"
    },
    {
      label: "Projects",
      to: "/projects"
    },
    {
      label: "Blog",
      to: "/blog"
    },
    {
      label: "Misc",
      to: "/misc"
    }
  ]

  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="content">
            <h1 className="left" style={{ width: '20rem', lineHeight: '2rem'}}>
              Samuel Morgan Anderson
            </h1>
            <Navbar className="right" links={navBarLinks}/>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
